services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: valyaint
      POSTGRES_PASSWORD: valyaint
      POSTGRES_DB: valyaint
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
